-- 1. Buat tabel product_events untuk menyimpan log produk baru & restock
create table public.product_events (
    id bigint generated by default as identity primary key,
    nama text not null,
    event_type text not null, -- 'new' atau 'restock'
    stock text,
    harga text,
    detected_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Buat tabel user_settings untuk menyimpan setingan masing-masing user
create table public.user_settings (
    chat_id text primary key,
    marketplace text default 'shopee'::text,
    admin_fee numeric default 6.5,
    markup_type text default 'percent'::text, -- 'percent' atau 'nominal'
    markup_value numeric default 0,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
